markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

name: Rob White
author_url: https://theoldsewingfactory.com
sitename: theoldsewingfactory.com
url: https://theoldsewingfactory.com
description: No more than my online scratchpad.
gravatar_url: https://s.gravatar.com/avatar/3d0c55237259b0b7e555272872a50f9f
