markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title/
rdiscount:
  extensions: [smart]

name: Rob White
sitename: theoldsewingfactory.com
url: http://theoldsewingfactory.com
description: No more than my online scratchpad.
twitter: ilivewithian
github: ilivewithian
gravatar_url: http://www.gravatar.com/avatar/3d0c55237259b0b7e555272872a50f9f?s=160
