baseURL = "https://theoldsewingfactory.com/"
languageCode = "en-us"
title = "The Old Sewing Factory"
theme = "hugo-ink"
paginate = 10

googleAnalytics = "UA-1566412-7"
disqusShortname = "theoldsewingfactory"

[params]
	avatar = "/images/avatar.png"
	disableDisqusTypes = ["page"]
	featherIconsCDN = true

[permalinks]
	posts = "/:year/:month/:title/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ilivewithian/"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/ilivewithian/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"